name: Publish package to GitHub Packages
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Cache local Maven repository
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            ${{ runner.os }}-maven-
      - name: Build release artifacts
        run: mvn -B package -DskipTests
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Upload release artifacts
        uses: actions/upload-release-asset@v1
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: $(curl -sL https://api.github.com/repos/j3t/jenkins-pipeline-cache-plugin/releases/tags/$VERSION | jq .upload_url)
          asset_path: ./target/jenkins-pipeline-cache.hpi
          asset_name: jenkins-pipeline-cache-$VERSION.hpi
          asset_content_type: application/zip